<?php

declare(strict_types=1);

namespace Ship\Support;

use Composer\InstalledVersions;

/**
 * The installed php-ship/ship version, used to detect when a project's published stub files
 * (ship/Dockerfile, ship/nginx/default.conf, ...) were generated by a different version than
 * what's actually installed now -- see InitCommand::publishStubs() (writes the marker) and
 * UpCommand (reads it to warn on mismatch).
 */
final class ShipVersion
{
    public static function current(): ?string
    {
        try {
            return InstalledVersions::getPrettyVersion('php-ship/ship');
        } catch (\OutOfBoundsException) {
            return null;
        }
    }
}
