<?php

declare(strict_types=1);

namespace Ship\Docker;

/**
 * Renders the shell script for the prod stage's ENTRYPOINT. Generated fresh by `ship up --prod` -- not
 * a static stub, since its content depends on which FrameworkAdapter matches. Deliberately a simple
 * shell script, not PHP -- it must run before the app container's PHP process starts at all here.
 */
final class EntrypointScriptBuilder
{
    /**
     * @param list<string> $releaseCommands framework adapters'
     *        FrameworkAdapter::releaseCommands(), already flattened
     */
    public function build(array $releaseCommands): string
    {
        $lines = [
            '#!/bin/sh',
            '',
            '# Generated by `ship up --prod` -- do not edit by hand, it will be',
            '# overwritten on the next `ship up --prod`. Runs once per container',
            '# boot, before the real process starts, so real runtime secrets',
            '# (injected via compose environment:/env_file:, never baked into',
            '# the image) are present for anything here that needs them,',
            '# e.g. Laravel\'s artisan optimize or Symfony\'s cache:clear.',
            'set -e',
            '',
        ];

        foreach ($releaseCommands as $command) {
            $lines[] = $command;
        }

        $lines[] = '';
        // exec (not a plain call) replaces this script's process rather
        // than spawning a child of it, so the real server ends up as
        // PID 1 -- otherwise `docker stop`'s SIGTERM hits this shell
        // instead of php-fpm/octane, and the container only dies on the
        // slower SIGKILL timeout.
        $lines[] = 'exec "$@"';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
