<?php

declare(strict_types=1);

namespace Ship\Docker;

/**
 * Renders the shell script for the prod stage's ENTRYPOINT. Generated fresh by `ship up --prod` -- not
 * a static stub, since its content depends on which FrameworkAdapter matches. Deliberately a simple
 * shell script, not PHP -- it must run before the app container's PHP process starts at all here.
 */
final class EntrypointScriptBuilder
{
    /**
     * @param list<string> $releaseCommands framework adapters'
     *        FrameworkAdapter::releaseCommands(), already flattened
     */
    public function build(array $releaseCommands): string
    {
        $lines = [
            '#!/bin/sh',
            '',
            '# Generated by `ship up --prod` -- do not edit by hand, it will be',
            '# overwritten on the next `ship up --prod`. Runs once per container',
            '# boot, before the real process starts, so real runtime secrets',
            '# (injected via compose environment:/env_file:, never baked into',
            '# the image) are present for anything here that needs them,',
            '# e.g. Laravel\'s artisan optimize or Symfony\'s cache:clear.',
            'set -e',
            '',
        ];

        foreach ($releaseCommands as $command) {
            $lines[] = $command;
        }

        $lines[] = '';
        // Everything up to here (image build, this script's own release commands -- e.g. artisan
        // optimize's view cache) runs as root, but plain php-fpm's request-handling workers run as
        // www-data (its own pool config, not something this script controls) -- without this,
        // anything a worker needs to write at request time (a view Laravel didn't pre-compile,
        // Symfony's cache warming up further) hits a permission error against root-owned files.
        // Only the directories a framework actually writes to at runtime, not the whole tree --
        // recursively chowning vendor/ too adds tens of seconds to every boot for no benefit, and
        // once blocked php-fpm from ever starting at all on a real Laravel app's vendor/ size.
        // "database" is in this list for Laravel's own default fresh-install setup: SQLite, both
        // as the main DB connection and (Laravel 11+) the "database" session/cache driver, with
        // database.sqlite living outside storage/ entirely -- SQLite needs to write both the file
        // and its parent directory (for journal/WAL files), so the directory itself has to be
        // included, not just chmod-ing the file. Existence-checked so this stays
        // framework-agnostic: harmless (nothing to do) for a framework using none of these paths,
        // and harmless for Octane runtimes either way since the whole process stays root there
        // regardless.
        $lines[] = 'for dir in storage bootstrap/cache database var; do';
        $lines[] = '    [ -d "$dir" ] && chown -R www-data:www-data "$dir"';
        $lines[] = 'done';
        $lines[] = '';
        // Decided per container at runtime, not baked into this file: the same image (and so this
        // one script) backs containers that need opposite things. php-fpm's master has to start as
        // root to then drop each *worker* to www-data itself, but an Octane server, or a process
        // like Horizon or the scheduler, is its own long-lived program with no such split -- left
        // alone it runs as root, every request handler included. The generated compose file sets
        // SHIP_RUN_AS on exactly those services. Skipped (stays root) where su-exec doesn't exist,
        // i.e. FrankenPHP's Debian image -- see docs/roadmap.md.
        $lines[] = 'if [ -n "$SHIP_RUN_AS" ] && command -v su-exec >/dev/null 2>&1; then';
        $lines[] = '    exec su-exec "$SHIP_RUN_AS" "$@"';
        $lines[] = 'fi';
        // exec (not a plain call) replaces this script's process rather
        // than spawning a child of it, so the real server ends up as
        // PID 1 -- otherwise `docker stop`'s SIGTERM hits this shell
        // instead of php-fpm/octane, and the container only dies on the
        // slower SIGKILL timeout. su-exec (unlike su or sudo) exec()s the
        // target directly rather than forking a child under itself, so this
        // holds when dropping privileges too.
        $lines[] = 'exec "$@"';
        $lines[] = '';

        return implode("\n", $lines);
    }
}
